### ISSUE TITLE
Test suite fails to run on ruby 2.1.2

### ISSUE THREAD

**Issue by microspino** [soveran/micromachine#20]
If i run **rake** or **rake test** i get:
```
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
```
and the suite stops with the error

```
MiniTest::Unit::TestCase is now Minitest::Test. From /Users/xxx/.rbenv/versions/2.1.2/lib/ruby/2.1.0/test/unit/testcase.rb:8:in `<module:Unit>'
/Users/xxx/.rbenv/versions/2.1.2/lib/ruby/2.1.0/test/unit.rb:676:in `<class:Runner>': undefined method `_run_suite' for class `Test::Unit::Runner' (NameError)
```

I'm on OS X Yosemite (v 10.10)  with
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
installed with rbenv

In order to have the test suite working i had to:
```
rbenv local 1.9.3-p547
gem install contest
rake
```

---

Side note: I've tried to use **dep install** to get **contest** installed but it failed with:
```
gem install contest:0.1.3
ERROR:  Could not find a valid gem 'contest:0.1.3' (>= 0) in any repository
```

**Comment by jdecuirm** [comment]
In Order to run my tests with rake i had to change require 'test/unit' to require 'minitest/autorun' and then in the class i had to change as follows:

class TestClass < Test::Unit::TestCase to class TestClass < Minitest::Test and it should be working, but still i have problems with assert_raise! there's an error i can't fix yet.

**Comment by soveran** [comment]
It's using [cutest](https://github.com/djanowski/cutest) now, and you can run the tests with `make`.
